### ISSUE TITLE
How to use AucTex shortcuts inside Doconce-mode

### ISSUE THREAD

**Issue by ofenerci** [larstvei/Doconce-mode#1]
Hello, 
I am using your Doconce-mode in for my editing Doconce files in Emacs. I would like to use AucTeX short commands inside Doconce-mode to save typing. For example, in AucTex I could insert an environment `C-c C-e` to select an environment type. 

Yasnippet may look more suitable than AucTeX. There is no problem using Yasnippet inside Doconce( it is really convenient to speed your typing LaTeX commands.) 

Thanks, 
Ozhan

**Comment by larstvei** [comment]
Hi!

Wow, I had no idea that _anyone_ used this mode!

What might be a nice solution for you is creating a small minor mode which activates the keymap AucTeX provides. Such a minor mode might look something like this:

```elisp
(define-minor-mode custom-bindings-mode
    "A mode that activates custom-bindings."
    t nil custom-bindings-map)
```

where you replace `custom-bindings-map` with whatever keymap you want. I think the keymap you want is `ConTeXt-mode-map`.

To enable this small minor mode along with doconce-mode you can do something like this:
```elisp
(add-hook 'doconce-mode-hook 'custom-bindings-mode)
```

**Comment by ofenerci** [comment]
Hello, 
I tried your advise but it didn't work. Is `doconce-mode` a major-mode or minor-mode? If I make  it a minor mode, I could use inside AucTeX. 

There is one more issue;  I would like to get a live preview (pdf or html). You could add some items into doconce-mode such that it automatically compiles the document whenever I save the document. It would be also good to add a live preview.

**Comment by larstvei** [comment]
I just noticed that the code above enables the mode by default; then the hook would cause it to be disabled, which might be why it didn't work. Try the following:

```elisp
(define-minor-mode auctex-minor-mode
  "A mode that activates custom-bindings."
  nil nil ConTeXt-mode-map)
```

I don't plan on developing this mode any further as I've never used it and don't plan to use it in the future, but you can probably roll you own for solutions to the problems you mention.

You can, for instance, use the `compile` command for compilation, and add `recompile` to the `after-save-hook` to get automatic compilation.

Getting live preview might not be quite as straight forward but should be possible. Check out [pdf-tools](https://github.com/politza/pdf-tools) for a nice(r) PDF viewr in Emacs. If you're able to detect when a compilation is finished, then you can call `pdf-view-revert-buffer`.
